export const LOCATIONS = {
  Afghanistan: {
    country: 'Afghanistan',
    iso2: 'AF',
    iso3: 'AFG',
  },
  Albania: {
    country: 'Albania',
    iso2: 'AL',
    iso3: 'ALB',
  },
  Algeria: {
    country: 'Algeria',
    iso2: 'DZ',
    iso3: 'DZA',
  },
  'American Samoa': {
    country: 'American Samoa',
    iso2: 'AS',
    iso3: 'ASM',
  },
  Andorra: {
    country: 'Andorra',
    iso2: 'AD',
    iso3: 'AND',
  },
  Angola: {
    country: 'Angola',
    iso2: 'AO',
    iso3: 'AGO',
  },
  Anguilla: {
    country: 'Anguilla',
    iso2: 'AI',
    iso3: 'AIA',
  },
  Antarctica: {
    country: 'Antarctica',
    iso2: 'AQ',
    iso3: 'ATA',
  },
  'Antigua and Barbuda': {
    country: 'Antigua and Barbuda',
    iso2: 'AG',
    iso3: 'ATG',
  },
  Argentina: {
    country: 'Argentina',
    iso2: 'AR',
    iso3: 'ARG',
  },
  Armenia: {
    country: 'Armenia',
    iso2: 'AM',
    iso3: 'ARM',
  },
  Aruba: {
    country: 'Aruba',
    iso2: 'AW',
    iso3: 'ABW',
  },
  Australia: {
    country: 'Australia',
    iso2: 'AU',
    iso3: 'AUS',
  },
  Austria: {
    country: 'Austria',
    iso2: 'AT',
    iso3: 'AUT',
  },
  Azerbaijan: {
    country: 'Azerbaijan',
    iso2: 'AZ',
    iso3: 'AZE',
  },
  Bahamas: {
    country: 'Bahamas',
    iso2: 'BS',
    iso3: 'BHS',
  },
  Bahrain: {
    country: 'Bahrain',
    iso2: 'BH',
    iso3: 'BHR',
  },
  Bangladesh: {
    country: 'Bangladesh',
    iso2: 'BD',
    iso3: 'BGD',
  },
  Barbados: {
    country: 'Barbados',
    iso2: 'BB',
    iso3: 'BRB',
  },
  Belarus: {
    country: 'Belarus',
    iso2: 'BY',
    iso3: 'BLR',
  },
  Belgium: {
    country: 'Belgium',
    iso2: 'BE',
    iso3: 'BEL',
  },
  Belize: {
    country: 'Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
  },
  Benin: {
    country: 'Benin',
    iso2: 'BJ',
    iso3: 'BEN',
  },
  Bermuda: {
    country: 'Bermuda',
    iso2: 'BM',
    iso3: 'BMU',
  },
  Bhutan: {
    country: 'Bhutan',
    iso2: 'BT',
    iso3: 'BTN',
  },
  Bolivia: {
    country: 'Bolivia',
    iso2: 'BO',
    iso3: 'BOL',
  },
  'Bosnia and Herzegovina': {
    country: 'Bosnia and Herzegovina',
    iso2: 'BA',
    iso3: 'BIH',
  },
  Botswana: {
    country: 'Botswana',
    iso2: 'BW',
    iso3: 'BWA',
  },
  Brazil: {
    country: 'Brazil',
    iso2: 'BR',
    iso3: 'BRA',
  },
  'British Indian Ocean Territory': {
    country: 'British Indian Ocean Territory',
    iso2: 'IO',
    iso3: 'IOT',
  },
  'British Virgin Islands': {
    country: 'British Virgin Islands',
    iso2: 'VG',
    iso3: 'VGB',
  },
  Brunei: {
    country: 'Brunei',
    iso2: 'BN',
    iso3: 'BRN',
  },
  Bulgaria: {
    country: 'Bulgaria',
    iso2: 'BG',
    iso3: 'BGR',
  },
  'Burkina Faso': {
    country: 'Burkina Faso',
    iso2: 'BF',
    iso3: 'BFA',
  },
  Burundi: {
    country: 'Burundi',
    iso2: 'BI',
    iso3: 'BDI',
  },
  Cambodia: {
    country: 'Cambodia',
    iso2: 'KH',
    iso3: 'KHM',
  },
  Cameroon: {
    country: 'Cameroon',
    iso2: 'CM',
    iso3: 'CMR',
  },
  Canada: {
    country: 'Canada',
    iso2: 'CA',
    iso3: 'CAN',
  },
  'Cape Verde': {
    country: 'Cape Verde',
    iso2: 'CV',
    iso3: 'CPV',
  },
  'Cayman Islands': {
    country: 'Cayman Islands',
    iso2: 'KY',
    iso3: 'CYM',
  },
  'Central African Republic': {
    country: 'Central African Republic',
    iso2: 'CF',
    iso3: 'CAF',
  },
  Chad: {
    country: 'Chad',
    iso2: 'TD',
    iso3: 'TCD',
  },
  Chile: {
    country: 'Chile',
    iso2: 'CL',
    iso3: 'CHL',
  },
  China: {
    country: 'China',
    iso2: 'CN',
    iso3: 'CHN',
  },
  'Christmas Island': {
    country: 'Christmas Island',
    iso2: 'CX',
    iso3: 'CXR',
  },
  'Cocos Islands': {
    country: 'Cocos Islands',
    iso2: 'CC',
    iso3: 'CCK',
  },
  Colombia: {
    country: 'Colombia',
    iso2: 'CO',
    iso3: 'COL',
  },
  Comoros: {
    country: 'Comoros',
    iso2: 'KM',
    iso3: 'COM',
  },
  'Cook Islands': {
    country: 'Cook Islands',
    iso2: 'CK',
    iso3: 'COK',
  },
  'Costa Rica': {
    country: 'Costa Rica',
    iso2: 'CR',
    iso3: 'CRI',
  },
  Croatia: {
    country: 'Croatia',
    iso2: 'HR',
    iso3: 'HRV',
  },
  Cuba: {
    country: 'Cuba',
    iso2: 'CU',
    iso3: 'CUB',
  },
  Curacao: {
    country: 'Curacao',
    iso2: 'CW',
    iso3: 'CUW',
  },
  Cyprus: {
    country: 'Cyprus',
    iso2: 'CY',
    iso3: 'CYP',
  },
  'Czech Republic': {
    country: 'Czech Republic',
    iso2: 'CZ',
    iso3: 'CZE',
  },
  'Democratic Republic of the Congo': {
    country: 'Democratic Republic of the Congo',
    iso2: 'CD',
    iso3: 'COD',
  },
  Denmark: {
    country: 'Denmark',
    iso2: 'DK',
    iso3: 'DNK',
  },
  Djibouti: {
    country: 'Djibouti',
    iso2: 'DJ',
    iso3: 'DJI',
  },
  Dominica: {
    country: 'Dominica',
    iso2: 'DM',
    iso3: 'DMA',
  },
  'Dominican Republic': {
    country: 'Dominican Republic',
    iso2: 'DO',
    iso3: 'DOM',
  },
  'East Timor': {
    country: 'East Timor',
    iso2: 'TL',
    iso3: 'TLS',
  },
  Ecuador: {
    country: 'Ecuador',
    iso2: 'EC',
    iso3: 'ECU',
  },
  Egypt: {
    country: 'Egypt',
    iso2: 'EG',
    iso3: 'EGY',
  },
  'El Salvador': {
    country: 'El Salvador',
    iso2: 'SV',
    iso3: 'SLV',
  },
  'Equatorial Guinea': {
    country: 'Equatorial Guinea',
    iso2: 'GQ',
    iso3: 'GNQ',
  },
  Eritrea: {
    country: 'Eritrea',
    iso2: 'ER',
    iso3: 'ERI',
  },
  Estonia: {
    country: 'Estonia',
    iso2: 'EE',
    iso3: 'EST',
  },
  Ethiopia: {
    country: 'Ethiopia',
    iso2: 'ET',
    iso3: 'ETH',
  },
  'Falkland Islands': {
    country: 'Falkland Islands',
    iso2: 'FK',
    iso3: 'FLK',
  },
  'Faroe Islands': {
    country: 'Faroe Islands',
    iso2: 'FO',
    iso3: 'FRO',
  },
  Fiji: {
    country: 'Fiji',
    iso2: 'FJ',
    iso3: 'FJI',
  },
  Finland: {
    country: 'Finland',
    iso2: 'FI',
    iso3: 'FIN',
  },
  France: {
    country: 'France',
    iso2: 'FR',
    iso3: 'FRA',
  },
  'French Polynesia': {
    country: 'French Polynesia',
    iso2: 'PF',
    iso3: 'PYF',
  },
  Gabon: {
    country: 'Gabon',
    iso2: 'GA',
    iso3: 'GAB',
  },
  Gambia: {
    country: 'Gambia',
    iso2: 'GM',
    iso3: 'GMB',
  },
  Georgia: {
    country: 'Georgia',
    iso2: 'GE',
    iso3: 'GEO',
  },
  Germany: {
    country: 'Germany',
    iso2: 'DE',
    iso3: 'DEU',
  },
  Ghana: {
    country: 'Ghana',
    iso2: 'GH',
    iso3: 'GHA',
  },
  Gibraltar: {
    country: 'Gibraltar',
    iso2: 'GI',
    iso3: 'GIB',
  },
  Greece: {
    country: 'Greece',
    iso2: 'GR',
    iso3: 'GRC',
  },
  Greenland: {
    country: 'Greenland',
    iso2: 'GL',
    iso3: 'GRL',
  },
  Grenada: {
    country: 'Grenada',
    iso2: 'GD',
    iso3: 'GRD',
  },
  Guam: {
    country: 'Guam',
    iso2: 'GU',
    iso3: 'GUM',
  },
  Guatemala: {
    country: 'Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
  },
  Guernsey: {
    country: 'Guernsey',
    iso2: 'GG',
    iso3: 'GGY',
  },
  Guinea: {
    country: 'Guinea',
    iso2: 'GN',
    iso3: 'GIN',
  },
  'Guinea-Bissau': {
    country: 'Guinea-Bissau',
    iso2: 'GW',
    iso3: 'GNB',
  },
  Guyana: {
    country: 'Guyana',
    iso2: 'GY',
    iso3: 'GUY',
  },
  Haiti: {
    country: 'Haiti',
    iso2: 'HT',
    iso3: 'HTI',
  },
  Honduras: {
    country: 'Honduras',
    iso2: 'HN',
    iso3: 'HND',
  },
  'Hong Kong': {
    country: 'Hong Kong',
    iso2: 'HK',
    iso3: 'HKG',
  },
  Hungary: {
    country: 'Hungary',
    iso2: 'HU',
    iso3: 'HUN',
  },
  Iceland: {
    country: 'Iceland',
    iso2: 'IS',
    iso3: 'ISL',
  },
  India: {
    country: 'India',
    iso2: 'IN',
    iso3: 'IND',
  },
  Indonesia: {
    country: 'Indonesia',
    iso2: 'ID',
    iso3: 'IDN',
  },
  Iran: {
    country: 'Iran',
    iso2: 'IR',
    iso3: 'IRN',
  },
  Iraq: {
    country: 'Iraq',
    iso2: 'IQ',
    iso3: 'IRQ',
  },
  Ireland: {
    country: 'Ireland',
    iso2: 'IE',
    iso3: 'IRL',
  },
  'Isle of Man': {
    country: 'Isle of Man',
    iso2: 'IM',
    iso3: 'IMN',
  },
  Israel: {
    country: 'Israel',
    iso2: 'IL',
    iso3: 'ISR',
  },
  Italy: {
    country: 'Italy',
    iso2: 'IT',
    iso3: 'ITA',
  },
  'Ivory Coast': {
    country: 'Ivory Coast',
    iso2: 'CI',
    iso3: 'CIV',
  },
  Jamaica: {
    country: 'Jamaica',
    iso2: 'JM',
    iso3: 'JAM',
  },
  Japan: {
    country: 'Japan',
    iso2: 'JP',
    iso3: 'JPN',
  },
  Jersey: {
    country: 'Jersey',
    iso2: 'JE',
    iso3: 'JEY',
  },
  Jordan: {
    country: 'Jordan',
    iso2: 'JO',
    iso3: 'JOR',
  },
  Kazakhstan: {
    country: 'Kazakhstan',
    iso2: 'KZ',
    iso3: 'KAZ',
  },
  Kenya: {
    country: 'Kenya',
    iso2: 'KE',
    iso3: 'KEN',
  },
  Kiribati: {
    country: 'Kiribati',
    iso2: 'KI',
    iso3: 'KIR',
  },
  Kosovo: {
    country: 'Kosovo',
    iso2: 'XK',
    iso3: 'XKX',
  },
  Kuwait: {
    country: 'Kuwait',
    iso2: 'KW',
    iso3: 'KWT',
  },
  Kyrgyzstan: {
    country: 'Kyrgyzstan',
    iso2: 'KG',
    iso3: 'KGZ',
  },
  Laos: {
    country: 'Laos',
    iso2: 'LA',
    iso3: 'LAO',
  },
  Latvia: {
    country: 'Latvia',
    iso2: 'LV',
    iso3: 'LVA',
  },
  Lebanon: {
    country: 'Lebanon',
    iso2: 'LB',
    iso3: 'LBN',
  },
  Lesotho: {
    country: 'Lesotho',
    iso2: 'LS',
    iso3: 'LSO',
  },
  Liberia: {
    country: 'Liberia',
    iso2: 'LR',
    iso3: 'LBR',
  },
  Libya: {
    country: 'Libya',
    iso2: 'LY',
    iso3: 'LBY',
  },
  Liechtenstein: {
    country: 'Liechtenstein',
    iso2: 'LI',
    iso3: 'LIE',
  },
  Lithuania: {
    country: 'Lithuania',
    iso2: 'LT',
    iso3: 'LTU',
  },
  Luxembourg: {
    country: 'Luxembourg',
    iso2: 'LU',
    iso3: 'LUX',
  },
  Macau: {
    country: 'Macau',
    iso2: 'MO',
    iso3: 'MAC',
  },
  Macedonia: {
    country: 'Macedonia',
    iso2: 'MK',
    iso3: 'MKD',
  },
  Madagascar: {
    country: 'Madagascar',
    iso2: 'MG',
    iso3: 'MDG',
  },
  Malawi: {
    country: 'Malawi',
    iso2: 'MW',
    iso3: 'MWI',
  },
  Malaysia: {
    country: 'Malaysia',
    iso2: 'MY',
    iso3: 'MYS',
  },
  Maldives: {
    country: 'Maldives',
    iso2: 'MV',
    iso3: 'MDV',
  },
  Mali: {
    country: 'Mali',
    iso2: 'ML',
    iso3: 'MLI',
  },
  Malta: {
    country: 'Malta',
    iso2: 'MT',
    iso3: 'MLT',
  },
  'Marshall Islands': {
    country: 'Marshall Islands',
    iso2: 'MH',
    iso3: 'MHL',
  },
  Mauritania: {
    country: 'Mauritania',
    iso2: 'MR',
    iso3: 'MRT',
  },
  Mauritius: {
    country: 'Mauritius',
    iso2: 'MU',
    iso3: 'MUS',
  },
  Mayotte: {
    country: 'Mayotte',
    iso2: 'YT',
    iso3: 'MYT',
  },
  Mexico: {
    country: 'Mexico',
    iso2: 'MX',
    iso3: 'MEX',
  },
  Micronesia: {
    country: 'Micronesia',
    iso2: 'FM',
    iso3: 'FSM',
  },
  Moldova: {
    country: 'Moldova',
    iso2: 'MD',
    iso3: 'MDA',
  },
  Monaco: {
    country: 'Monaco',
    iso2: 'MC',
    iso3: 'MCO',
  },
  Mongolia: {
    country: 'Mongolia',
    iso2: 'MN',
    iso3: 'MNG',
  },
  Montenegro: {
    country: 'Montenegro',
    iso2: 'ME',
    iso3: 'MNE',
  },
  Montserrat: {
    country: 'Montserrat',
    iso2: 'MS',
    iso3: 'MSR',
  },
  Morocco: {
    country: 'Morocco',
    iso2: 'MA',
    iso3: 'MAR',
  },
  Mozambique: {
    country: 'Mozambique',
    iso2: 'MZ',
    iso3: 'MOZ',
  },
  Myanmar: {
    country: 'Myanmar',
    iso2: 'MM',
    iso3: 'MMR',
  },
  Namibia: {
    country: 'Namibia',
    iso2: 'NA',
    iso3: 'NAM',
  },
  Nauru: {
    country: 'Nauru',
    iso2: 'NR',
    iso3: 'NRU',
  },
  Nepal: {
    country: 'Nepal',
    iso2: 'NP',
    iso3: 'NPL',
  },
  Netherlands: {
    country: 'Netherlands',
    iso2: 'NL',
    iso3: 'NLD',
  },
  'Netherlands Antilles': {
    country: 'Netherlands Antilles',
    iso2: 'AN',
    iso3: 'ANT',
  },
  'New Caledonia': {
    country: 'New Caledonia',
    iso2: 'NC',
    iso3: 'NCL',
  },
  'New Zealand': {
    country: 'New Zealand',
    iso2: 'NZ',
    iso3: 'NZL',
  },
  Nicaragua: {
    country: 'Nicaragua',
    iso2: 'NI',
    iso3: 'NIC',
  },
  Niger: {
    country: 'Niger',
    iso2: 'NE',
    iso3: 'NER',
  },
  Nigeria: {
    country: 'Nigeria',
    iso2: 'NG',
    iso3: 'NGA',
  },
  Niue: {
    country: 'Niue',
    iso2: 'NU',
    iso3: 'NIU',
  },
  'North Korea': {
    country: 'North Korea',
    iso2: 'KP',
    iso3: 'PRK',
  },
  'Northern Mariana Islands': {
    country: 'Northern Mariana Islands',
    iso2: 'MP',
    iso3: 'MNP',
  },
  Norway: {
    country: 'Norway',
    iso2: 'NO',
    iso3: 'NOR',
  },
  Oman: {
    country: 'Oman',
    iso2: 'OM',
    iso3: 'OMN',
  },
  Pakistan: {
    country: 'Pakistan',
    iso2: 'PK',
    iso3: 'PAK',
  },
  Palau: {
    country: 'Palau',
    iso2: 'PW',
    iso3: 'PLW',
  },
  Palestine: {
    country: 'Palestine',
    iso2: 'PS',
    iso3: 'PSE',
  },
  Panama: {
    country: 'Panama',
    iso2: 'PA',
    iso3: 'PAN',
  },
  'Papua New Guinea': {
    country: 'Papua New Guinea',
    iso2: 'PG',
    iso3: 'PNG',
  },
  Paraguay: {
    country: 'Paraguay',
    iso2: 'PY',
    iso3: 'PRY',
  },
  Peru: {
    country: 'Peru',
    iso2: 'PE',
    iso3: 'PER',
  },
  Philippines: {
    country: 'Philippines',
    iso2: 'PH',
    iso3: 'PHL',
  },
  Pitcairn: {
    country: 'Pitcairn',
    iso2: 'PN',
    iso3: 'PCN',
  },
  Poland: {
    country: 'Poland',
    iso2: 'PL',
    iso3: 'POL',
  },
  Portugal: {
    country: 'Portugal',
    iso2: 'PT',
    iso3: 'PRT',
  },
  'Puerto Rico': {
    country: 'Puerto Rico',
    iso2: 'PR',
    iso3: 'PRI',
  },
  Qatar: {
    country: 'Qatar',
    iso2: 'QA',
    iso3: 'QAT',
  },
  'Republic of the Congo': {
    country: 'Republic of the Congo',
    iso2: 'CG',
    iso3: 'COG',
  },
  Reunion: {
    country: 'Reunion',
    iso2: 'RE',
    iso3: 'REU',
  },
  Romania: {
    country: 'Romania',
    iso2: 'RO',
    iso3: 'ROU',
  },
  Russia: {
    country: 'Russia',
    iso2: 'RU',
    iso3: 'RUS',
  },
  Rwanda: {
    country: 'Rwanda',
    iso2: 'RW',
    iso3: 'RWA',
  },
  'Saint Barthelemy': {
    country: 'Saint Barthelemy',
    iso2: 'BL',
    iso3: 'BLM',
  },
  'Saint Helena': {
    country: 'Saint Helena',
    iso2: 'SH',
    iso3: 'SHN',
  },
  'Saint Kitts and Nevis': {
    country: 'Saint Kitts and Nevis',
    iso2: 'KN',
    iso3: 'KNA',
  },
  'Saint Lucia': {
    country: 'Saint Lucia',
    iso2: 'LC',
    iso3: 'LCA',
  },
  'Saint Martin': {
    country: 'Saint Martin',
    iso2: 'MF',
    iso3: 'MAF',
  },
  'Saint Pierre and Miquelon': {
    country: 'Saint Pierre and Miquelon',
    iso2: 'PM',
    iso3: 'SPM',
  },
  'Saint Vincent and the Grenadines': {
    country: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    iso3: 'VCT',
  },
  Samoa: {
    country: 'Samoa',
    iso2: 'WS',
    iso3: 'WSM',
  },
  'San Marino': {
    country: 'San Marino',
    iso2: 'SM',
    iso3: 'SMR',
  },
  'Sao Tome and Principe': {
    country: 'Sao Tome and Principe',
    iso2: 'ST',
    iso3: 'STP',
  },
  'Saudi Arabia': {
    country: 'Saudi Arabia',
    iso2: 'SA',
    iso3: 'SAU',
  },
  Senegal: {
    country: 'Senegal',
    iso2: 'SN',
    iso3: 'SEN',
  },
  Serbia: {
    country: 'Serbia',
    iso2: 'RS',
    iso3: 'SRB',
  },
  Seychelles: {
    country: 'Seychelles',
    iso2: 'SC',
    iso3: 'SYC',
  },
  'Sierra Leone': {
    country: 'Sierra Leone',
    iso2: 'SL',
    iso3: 'SLE',
  },
  Singapore: {
    country: 'Singapore',
    iso2: 'SG',
    iso3: 'SGP',
  },
  'Sint Maarten': {
    country: 'Sint Maarten',
    iso2: 'SX',
    iso3: 'SXM',
  },
  Slovakia: {
    country: 'Slovakia',
    iso2: 'SK',
    iso3: 'SVK',
  },
  Slovenia: {
    country: 'Slovenia',
    iso2: 'SI',
    iso3: 'SVN',
  },
  'Solomon Islands': {
    country: 'Solomon Islands',
    iso2: 'SB',
    iso3: 'SLB',
  },
  Somalia: {
    country: 'Somalia',
    iso2: 'SO',
    iso3: 'SOM',
  },
  'South Africa': {
    country: 'South Africa',
    iso2: 'ZA',
    iso3: 'ZAF',
  },
  'South Korea': {
    country: 'South Korea',
    iso2: 'KR',
    iso3: 'KOR',
  },
  'South Sudan': {
    country: 'South Sudan',
    iso2: 'SS',
    iso3: 'SSD',
  },
  Spain: {
    country: 'Spain',
    iso2: 'ES',
    iso3: 'ESP',
  },
  'Sri Lanka': {
    country: 'Sri Lanka',
    iso2: 'LK',
    iso3: 'LKA',
  },
  Sudan: {
    country: 'Sudan',
    iso2: 'SD',
    iso3: 'SDN',
  },
  Suriname: {
    country: 'Suriname',
    iso2: 'SR',
    iso3: 'SUR',
  },
  'Svalbard and Jan Mayen': {
    country: 'Svalbard and Jan Mayen',
    iso2: 'SJ',
    iso3: 'SJM',
  },
  Swaziland: {
    country: 'Swaziland',
    iso2: 'SZ',
    iso3: 'SWZ',
  },
  Sweden: {
    country: 'Sweden',
    iso2: 'SE',
    iso3: 'SWE',
  },
  Switzerland: {
    country: 'Switzerland',
    iso2: 'CH',
    iso3: 'CHE',
  },
  Syria: {
    country: 'Syria',
    iso2: 'SY',
    iso3: 'SYR',
  },
  Taiwan: {
    country: 'Taiwan',
    iso2: 'TW',
    iso3: 'TWN',
  },
  Tajikistan: {
    country: 'Tajikistan',
    iso2: 'TJ',
    iso3: 'TJK',
  },
  Tanzania: {
    country: 'Tanzania',
    iso2: 'TZ',
    iso3: 'TZA',
  },
  Thailand: {
    country: 'Thailand',
    iso2: 'TH',
    iso3: 'THA',
  },
  Togo: {
    country: 'Togo',
    iso2: 'TG',
    iso3: 'TGO',
  },
  Tokelau: {
    country: 'Tokelau',
    iso2: 'TK',
    iso3: 'TKL',
  },
  Tonga: {
    country: 'Tonga',
    iso2: 'TO',
    iso3: 'TON',
  },
  'Trinidad and Tobago': {
    country: 'Trinidad and Tobago',
    iso2: 'TT',
    iso3: 'TTO',
  },
  Tunisia: {
    country: 'Tunisia',
    iso2: 'TN',
    iso3: 'TUN',
  },
  Turkey: {
    country: 'Turkey',
    iso2: 'TR',
    iso3: 'TUR',
  },
  Turkmenistan: {
    country: 'Turkmenistan',
    iso2: 'TM',
    iso3: 'TKM',
  },
  'Turks and Caicos Islands': {
    country: 'Turks and Caicos Islands',
    iso2: 'TC',
    iso3: 'TCA',
  },
  Tuvalu: {
    country: 'Tuvalu',
    iso2: 'TV',
    iso3: 'TUV',
  },
  'U.S. Virgin Islands': {
    country: 'U.S. Virgin Islands',
    iso2: 'VI',
    iso3: 'VIR',
  },
  Uganda: {
    country: 'Uganda',
    iso2: 'UG',
    iso3: 'UGA',
  },
  Ukraine: {
    country: 'Ukraine',
    iso2: 'UA',
    iso3: 'UKR',
  },
  'United Arab Emirates': {
    country: 'United Arab Emirates',
    iso2: 'AE',
    iso3: 'ARE',
  },
  'United Kingdom': {
    country: 'United Kingdom',
    iso2: 'GB',
    iso3: 'GBR',
  },
  'United States': {
    country: 'United States',
    iso2: 'US',
    iso3: 'USA',
  },
  Uruguay: {
    country: 'Uruguay',
    iso2: 'UY',
    iso3: 'URY',
  },
  Uzbekistan: {
    country: 'Uzbekistan',
    iso2: 'UZ',
    iso3: 'UZB',
  },
  Vanuatu: {
    country: 'Vanuatu',
    iso2: 'VU',
    iso3: 'VUT',
  },
  Vatican: {
    country: 'Vatican',
    iso2: 'VA',
    iso3: 'VAT',
  },
  Venezuela: {
    country: 'Venezuela',
    iso2: 'VE',
    iso3: 'VEN',
  },
  Vietnam: {
    country: 'Vietnam',
    iso2: 'VN',
    iso3: 'VNM',
  },
  'Wallis and Futuna': {
    country: 'Wallis and Futuna',
    iso2: 'WF',
    iso3: 'WLF',
  },
  'Western Sahara': {
    country: 'Western Sahara',
    iso2: 'EH',
    iso3: 'ESH',
  },
  Yemen: {
    country: 'Yemen',
    iso2: 'YE',
    iso3: 'YEM',
  },
  Zambia: {
    country: 'Zambia',
    iso2: 'ZM',
    iso3: 'ZMB',
  },
  Zimbabwe: {
    country: 'Zimbabwe',
    iso2: 'ZW',
    iso3: 'ZWE',
  },
};

export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos Islands',
  'Colombia',
  'Comoros',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'North Korea',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barthelemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'U.S. Virgin Islands',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Vietnam',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];
